emr/urls.py
from django.urls import path
from django.views.defaults import page_not_found

from .views import (
    DataTablesLanguageFile,
    MedicalRecordCreate,
    MedicalRecordUpdate,
    PatientCreate,
    PatientDelete,
    PatientDetail,
    PatientList,
    PatientListApi,
    PatientUpdate,
)

app_name = "emr"
js_kwargs = {"exception": None}
urlpatterns = [
    # API
    path("api/patients/", PatientListApi.as_view(), name="api-patient-list"),
    path(
        "api/datatables/language/",
        DataTablesLanguageFile.as_view(),
        name="api-datatables-language",
    ),
    # Patients
    path("patients/", PatientList.as_view(), name="patient-list"),
    path("patients/<int:pk>/", PatientDetail.as_view(), name="patient-detail"),
    path("patients/create/", PatientCreate.as_view(), name="patient-create"),
    path("patients/update/<int:pk>/", PatientUpdate.as_view(), name="patient-update"),
    path("patients/delete/<int:pk>/", PatientDelete.as_view(), name="patient-delete"),
    # Argument-less paths for patients/list.js
    path("patients/", page_not_found, js_kwargs, "patient-detail"),
    path("patients/update/", page_not_found, js_kwargs, "patient-update"),
    path("patients/delete/", page_not_found, js_kwargs, "patient-delete"),
    # Medical Records
    path(
        "medical-records/create/<int:patient_pk>/",
        MedicalRecordCreate.as_view(),
        name="medical-record-create",
    ),
    path(
        "medical-records/update/<int:pk>/",
        MedicalRecordUpdate.as_view(),
        name="medical-record-update",
    ),
]

pyfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base_site.urls")),
    path("emr/", include("emr.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emr/models.py
from datetime import date
from uuid import uuid4

from dateutil.relativedelta import relativedelta
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


def patient_profile_picture_path(instance, filename):
    return "profile_pictures/{0}.jpg".format(str(uuid4()))


class Patient(models.Model):
    NOT_KNOWN = 0
    MALE = 1
    FEMALE = 2
    NOT_APPLICABLE = 9

    SEX_CHOICES = [
        (NOT_KNOWN, _("Not Known")),
        (MALE, _("Male")),
        (FEMALE, _("Female")),
        (NOT_APPLICABLE, _("Not Applicable")),
    ]

    identification = models.CharField(_("Identification"), max_length=20, unique=True)
    date_added = models.DateTimeField(_("Date Added"), auto_now_add=True)
    profile_picture = models.ImageField(
        _("Profile Picture"),
        upload_to=patient_profile_picture_path,
        blank=True,
    )
    first_name = models.CharField(_("First Name"), max_length=45)
    last_name = models.CharField(_("Last Name"), max_length=45)
    sex = models.IntegerField(_("Sex"), choices=SEX_CHOICES, default=NOT_KNOWN)
    date_of_birth = models.DateField(_("Date of Birth"))
    occupation = models.CharField(_("Occupation"), max_length=45)
    phone_number = models.CharField(_("Phone Number"), max_length=8)
    address = models.TextField(_("Address"))

    class Meta:
        verbose_name = _("Patient")
        verbose_name_plural = _("Patients")

        ordering = ["id"]

    def __str__(self):
        return self.full_name()

    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def sex_verbose(self):
        return dict(self.SEX_CHOICES)[self.sex]

    def age(self):
        return relativedelta(date.today(), self.date_of_birth).years

    def has_medical_record(self):
        return hasattr(self, "medical_record")

    def has_profile_picture(self):
        return bool(self.profile_picture)

    def clean(self):
        if self.date_of_birth > date.today():
            raise ValidationError({"date_of_birth": _("Invalid date of birth.")})


class MedicalRecord(models.Model):
    patient = models.OneToOneField(
        Patient, on_delete=models.CASCADE, related_name="medical_record"
    )
    current_condition = models.TextField(_("Current Condition"))
    current_treatment = models.TextField(_("Current Treatment"))
    reference = models.TextField(_("Reference"))
    physical_exploration = models.TextField(_("Physical Exploration"))
    diagnosis = models.TextField(_("Diagnosis"))
    treatment_to_follow = models.TextField(_("Treatment to Follow"))
    additional_notes = models.TextField(_("Additional Notes"), blank=True)
    last_modified = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        db_table = "emr_medical_record"
        verbose_name = _("Medical Record")
        verbose_name_plural = _("Medical Records")

    def __str__(self):
        return _("%(patient_full_name)s's Medical Record") % {
            "patient_full_name": self.patient.full_name()
        }

emr/forms.py
from django.forms import ModelForm

from .models import MedicalRecord


class MedicalRecordForm(ModelForm):
    class Meta:
        model = MedicalRecord
        exclude = ["patient"]

emr/views.py
import json
from importlib.resources import files

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import get_language
from django.utils.translation import gettext_lazy as _
from django.utils.translation import pgettext
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    TemplateView,
    UpdateView,
    View,
)

from .forms import MedicalRecordForm
from .models import MedicalRecord, Patient

# Create your views here.


class PatientList(LoginRequiredMixin, TemplateView):
    template_name = "emr/patients/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["js_data"] = {
            "urls": {
                "datatablesLanguage": reverse("emr:api-datatables-language"),
                "patientList": reverse("emr:api-patient-list"),
                "viewPatient": reverse("emr:patient-detail"),
                "updatePatient": reverse("emr:patient-update"),
                "deletePatient": reverse("emr:patient-delete"),
            },
            "lang": {
                "view": pgettext("verb", "View"),
                "edit": _("Edit"),
                "delete": _("Remove"),
            },
        }
        return context


class PatientListApi(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        patient_fields = ["id", "identification", "first_name", "last_name"]
        patient_list = Patient.objects.values(*patient_fields)

        return JsonResponse({"data": list(patient_list)})


class PatientDetail(LoginRequiredMixin, DetailView):
    model = Patient
    template_name = "emr/patients/detail.html"


class PatientCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Patient
    template_name = "emr/patients/create_form.html"
    success_url = reverse_lazy("emr:patient-list")
    fields = "__all__"
    success_message = _("Patient %(patient_full_name)s added")

    def get_success_message(self, cleaned_data):
        patient = self.object
        return self.success_message % dict(patient_full_name=patient.full_name())


class PatientUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Patient
    template_name = "emr/patients/update_form.html"
    fields = "__all__"
    success_message = _("Personal information updated")

    def get_success_url(self):
        patient = self.get_object()
        return reverse("emr:patient-detail", args=[patient.id])


class PatientDelete(LoginRequiredMixin, DeleteView):
    model = Patient
    template_name = "emr/patients/confirm_delete.html"
    success_url = reverse_lazy("emr:patient-list")
    success_message = _("Patient %(patient_full_name)s removed")

    # HACK: DeleteView currently does not support SuccessMessageMixin, so this method had to be overridden
    def delete(self, request, *args, **kwargs):
        patient = self.get_object()
        messages.success(
            request, self.success_message % dict(patient_full_name=patient.full_name())
        )
        return super().delete(self, request, *args, **kwargs)


class MedicalRecordCreate(LoginRequiredMixin, View):
    template_name = "emr/medical_records/create_form.html"
    form_class = MedicalRecordForm
    model = MedicalRecord
    success_message = _("Medical record created")

    def get(self, request, patient_pk):
        patient = get_object_or_404(Patient, pk=patient_pk)
        return render(
            request, self.template_name, {"form": self.form_class(), "patient": patient}
        )

    def post(self, request, patient_pk):
        patient = get_object_or_404(Patient, pk=patient_pk)
        form = self.form_class(request.POST)

        if form.is_valid():
            medical_record = form.save(commit=False)
            medical_record.patient = patient
            medical_record.save()

            messages.success(request, self.success_message)
            return redirect("emr:patient-detail", patient.id)

        else:
            return render(
                request, self.template_name, {"form": form, "patient": patient}
            )


class MedicalRecordUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = MedicalRecord
    fields = [
        "current_condition",
        "current_treatment",
        "reference",
        "physical_exploration",
        "diagnosis",
        "treatment_to_follow",
        "additional_notes",
    ]
    template_name = "emr/medical_records/update_form.html"
    success_message = _("Medical record updated")

    def get_success_url(self):
        medical_record = self.get_object()
        patient_id = medical_record.patient.id
        return reverse("emr:patient-detail", args=[patient_id])


class DataTablesLanguageFile(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        # HACK: Small patch to localize DataTables
        if get_language() == "es":
            with (
                files("emr.resources.datatables")
                .joinpath("spanish.json")
                .open("r") as language_file
            ):
                return JsonResponse(json.load(language_file))
        else:
            return JsonResponse(None, safe=False)

emr/templates/emr/medical_records/create_form.html
{% extends "base.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url 'index' %}">{% translate "Home" %}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'emr:patient-list' %}">{% translate "Patients" %}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'emr:patient-detail' patient.id %}">{{ patient.full_name }}</a></li>
  <li class="breadcrumb-item active">{% translate "Create Medical Record" %}</li>
</ol>

<form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-success">{% translate "Submit" %}</button>
  <a class="btn btn-danger" href="{% url 'emr:patient-detail' patient.id %}">{% translate "Cancel" %}</a>
</form>
{% endblock %}

emr/templates/emr/medical_records/detail_snippet.html
{% load i18n %}

<div class="accordion-item">
  <h1 class="accordion-header">
    <button class="accordion-button" type="button" data-bs-toggle="collapse"
        data-bs-target="#medical-record">
      {% translate "Medical Record" %}
    </button>
  </h1>

  <div id="medical-record" class="accordion-collapse collapse show"
      data-bs-parent="#detail-accordion">
    <div class="accordion-body">
      <ul class="list-group list-group-flush">
        {% if patient.has_medical_record %}
          {% with medical_record=patient.medical_record %}
            <li class="list-group-item">
              <a class="btn btn-primary" href="{% url 'emr:medical-record-update' medical_record.id %}">
                {% translate "Update Medical Record" %}
              </a>
            </li>
            <li class="list-group-item">
              <table class="table table-striped">
                <tr>
                  <th>{% translate "Last Modified" %}</th>
                  <td>{{ medical_record.last_modified|date:"j/n/Y P" }}</td>
                </tr>
                <tr>
                  <th>{% translate "Current Condition" %}</th>
                  <td>{{ medical_record.current_condition }}</td>
                </tr>
                <tr>
                  <th>{% translate "Current Treatment" %}</th>
                  <td>{{ medical_record.current_treatment }}</td>
                </tr>
                <tr>
                  <th>{% translate "Reference" %}</th>
                  <td>{{ medical_record.reference }}</td>
                </tr>
                <tr>
                  <th>{% translate "Physical Exploration" %}</th>
                  <td>{{ medical_record.physical_exploration }}</td>
                </tr>
                <tr>
                  <th>{% translate "Diagnosis" %}</th>
                  <td>{{ medical_record.diagnosis }}</td>
                </tr>
                <tr>
                  <th>{% translate "Treatment to Follow" %}</th>
                  <td>{{ medical_record.treatment_to_follow }}</td>
                </tr>
                <tr>
                  <th>{% translate "Additional Notes" %}</th>
                  <td>{{ medical_record.additional_notes }}</td>
                </tr>
              </table>
            </li>
          {% endwith %}
        {% else %}
          <li class="list-group-item">
            <a class="btn btn-success" href="{% url 'emr:medical-record-create' patient.id %}">
              {% translate "Create Medical Record" %}
            </a>
          </li>
          <li class="list-group-item">
            {% translate "This patient doesn't have a medical record yet." %}
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>

emr/templates/emr/medical_records/update_form.html
{% extends "base.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
{% with medical_record=object patient=object.patient %}

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url 'index' %}">{% translate "Home" %}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'emr:patient-list' %}">{% translate "Patients" %}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'emr:patient-detail' patient.id %}">{{ patient }}</a></li>
  <li class="breadcrumb-item active">{% translate "Update Medical Record" %}</li>
</ol>

<form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-success">{% translate "Submit" %}</button>
  <a class="btn btn-danger" href="{% url 'emr:patient-detail' patient.id %}">{% translate "Cancel" %}</a>
</form>
{% endwith %}
{% endblock %}