emr/urls.py
from django.urls import path
from django.views.defaults import page_not_found

from .views import (
    DataTablesLanguageFile,
    MedicalRecordCreate,
    MedicalRecordUpdate,
    PatientCreate,
    PatientDelete,
    PatientDetail,
    PatientList,
    PatientListApi,
    PatientUpdate,
)

app_name = "emr"
js_kwargs = {"exception": None}
urlpatterns = [
    # API
    path("api/patients/", PatientListApi.as_view(), name="api-patient-list"),
    path(
        "api/datatables/language/",
        DataTablesLanguageFile.as_view(),
        name="api-datatables-language",
    ),
    # Patients
    path("patients/", PatientList.as_view(), name="patient-list"),
    path("patients/<int:pk>/", PatientDetail.as_view(), name="patient-detail"),
    path("patients/create/", PatientCreate.as_view(), name="patient-create"),
    path("patients/update/<int:pk>/", PatientUpdate.as_view(), name="patient-update"),
    path("patients/delete/<int:pk>/", PatientDelete.as_view(), name="patient-delete"),
    # Argument-less paths for patients/list.js
    path("patients/", page_not_found, js_kwargs, "patient-detail"),
    path("patients/update/", page_not_found, js_kwargs, "patient-update"),
    path("patients/delete/", page_not_found, js_kwargs, "patient-delete"),
    # Medical Records
    path(
        "medical-records/create/<int:patient_pk>/",
        MedicalRecordCreate.as_view(),
        name="medical-record-create",
    ),
    path(
        "medical-records/update/<int:pk>/",
        MedicalRecordUpdate.as_view(),
        name="medical-record-update",
    ),
]

pyfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base_site.urls")),
    path("emr/", include("emr.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pyfolio/base.html
{% load static bootstrap3 %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    <link rel="stylesheet" href="{% static "pyfolio/css/base.css" %}" type="text/css" media="all" />
    <link rel="icon" href="{% static "pyfolio/img/favicon.ico" %}" type="image/x-icon" />
    {% block content_css %}{% endblock %}
    <title>Folio</title>
  </head>

  <body>
    <div class="container">
      {% include "pyfolio/navbar.html" %}

      {% block content %}{% endblock %}
    </div>

    {% include "footer.html" %}
  </body>
</html>

templates/pyfolio/index.html
{% extends "pyfolio/base.html" %}
{% load static i18n %}

{% block content_css %}
<link rel="stylesheet" href="{% static "pyfolio/css/index.css" %}" type="text/css" media="all" />
{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1>{% trans "Welcome to Folio" %}</h1>
  <p>{% trans "Medical records, made easy" %}</p>

  {% if user.is_authenticated %}
  <a class="btn btn-lg btn-success" href="{% url "emr:patient-list" %}">{% trans "View Patients" %}</a>
  {% else %}
  <a class="btn btn-lg btn-success" href="{% url "login" %}">{% trans "Sign In" %}</a>
  {% endif %}
</div>
{% endblock %}