emr/urls.py
from django.urls import path
from django.views.defaults import page_not_found

from .views import (
    DataTablesLanguageFile,
    MedicalRecordCreate,
    MedicalRecordUpdate,
    PatientCreate,
    PatientDelete,
    PatientDetail,
    PatientList,
    PatientListApi,
    PatientUpdate,
)

app_name = "emr"
js_kwargs = {"exception": None}
urlpatterns = [
    # API
    path("api/patients/", PatientListApi.as_view(), name="api-patient-list"),
    path(
        "api/datatables/language/",
        DataTablesLanguageFile.as_view(),
        name="api-datatables-language",
    ),
    # Patients
    path("patients/", PatientList.as_view(), name="patient-list"),
    path("patients/<int:pk>/", PatientDetail.as_view(), name="patient-detail"),
    path("patients/create/", PatientCreate.as_view(), name="patient-create"),
    path("patients/update/<int:pk>/", PatientUpdate.as_view(), name="patient-update"),
    path("patients/delete/<int:pk>/", PatientDelete.as_view(), name="patient-delete"),
    # Argument-less paths for patients/list.js
    path("patients/", page_not_found, js_kwargs, "patient-detail"),
    path("patients/update/", page_not_found, js_kwargs, "patient-update"),
    path("patients/delete/", page_not_found, js_kwargs, "patient-delete"),
    # Medical Records
    path(
        "medical-records/create/<int:patient_pk>/",
        MedicalRecordCreate.as_view(),
        name="medical-record-create",
    ),
    path(
        "medical-records/update/<int:pk>/",
        MedicalRecordUpdate.as_view(),
        name="medical-record-update",
    ),
]

patients/urls.py
from django.conf.urls import url

from .views import (Index, PatientCreate, PatientDelete, PatientDetail,
                    PatientList, PatientUpdate)

app_name = 'patients'
urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^patients$', PatientList.as_view(), name="patient-list"),
    url(r'^patients/(?P<pk>\d+)$', PatientDetail.as_view(), name="patient-detail"),
    url(r'^patients/create$', PatientCreate.as_view(), name="patient-create"),
    url(r'^patients/update/(?P<pk>\d+)$', PatientUpdate.as_view(), name="patient-update"),
    url(r'^patients/delete/(?P<pk>\d+)$', PatientDelete.as_view(), name="patient-delete"),
]

pyfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base_site.urls")),
    path("emr/", include("emr.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import get_list_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from .models import Patient

# Create your views here.


SUCCESS_URL = reverse_lazy('patients:patient-list')

FIELDS = [
    'identification',
    'first_name',
    'last_name',
    'sex',
    'date_of_birth',
    'occupation',
    'phone_number',
    'address',
]


class Index(TemplateView):
    template_name = 'patients/index.html'


class PatientList(LoginRequiredMixin, ListView):
    model = Patient


class PatientDetail(LoginRequiredMixin, DetailView):
    model = Patient


class PatientCreate(LoginRequiredMixin, CreateView):
    model = Patient
    success_url = SUCCESS_URL
    fields = FIELDS
    template_name_suffix = '_create_form'


class PatientUpdate(LoginRequiredMixin, UpdateView):
    model = Patient
    success_url = SUCCESS_URL
    fields = FIELDS
    template_name_suffix = '_update_form'


class PatientDelete(LoginRequiredMixin, DeleteView):
    model = Patient
    success_url = SUCCESS_URL

patients/templates/patients/base.html
{% load static bootstrap3 %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    <link rel="stylesheet" href="{% static "patients/css/base.css" %}" type="text/css" media="all" />
    {% block content_css %}{% endblock %}
    <title>Folio</title>
  </head>

  <body>
    <div class="container">
      {% include "patients/navbar.html" %}

      {% block content %}{% endblock %}
    </div>
  </body>
</html>

patients/templates/patients/index.html
{% extends "patients/base.html" %}
{% load static i18n %}

{% block content_css %}
<link rel="stylesheet" href="{% static "patients/css/index.css" %}" type="text/css" media="all" />
{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1>{% trans "Welcome to Folio" %}</h1>
  <p>{% trans "Medical records, made easy" %}</p>

  {% if user.is_authenticated %}
  <a class="btn btn-lg btn-success" href="{% url "patients:patient-list" %}">{% trans "Patients" %}</a>
  {% else %}
  <a class="btn btn-lg btn-success" href="{% url "login" %}">{% trans "Sign In" %}</a>
  {% endif %}
</div>
{% endblock %}

patients/templates/patients/navbar.html
{% load i18n nav %}

{% trans "Sign Out" as sign_out %}
{% trans "Sign In" as sign_in %}

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main_navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "patients:index" %}">Folio</a>
    </div>

    <div class="collapse navbar-collapse" id="main_navbar">
      <ul class="nav navbar-nav navbar-right">

        {% if user.is_authenticated %}
          <li><p class="navbar-text">{% blocktrans %}Hello, {{ user }}{% endblocktrans %}</p></li>
          {% navlink "logout" sign_out %}
        {% else %}
          {% navlink "login" sign_in %}
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

patients/templates/patients/patient_confirm_delete.html
{% extends "patients/base.html" %}
{% load i18n %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <p>{% blocktrans %} Are you sure you want to remove "{{ object }}"? {% endblocktrans %}</p>
  <input class="btn btn-danger" type="submit" value="{% trans "Remove" %}">
</form>
{% endblock %}

patients/templates/patients/patient_create_form.html
{% extends "patients/base.html" %}
{% load i18n bootstrap3 %}

{% block content %}

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url "patients:index" %}">{% trans "Home" %}</a></li>
  <li class="breadcrumb-item"><a href="{% url "patients:patient-list" %}">{% trans "Patients" %}</a></li>
  <li class="breadcrumb-item active">{% trans "Add Patient" %}</li>
</ol>

<form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-success">{% trans "Submit" %}</button>
  <a class="btn btn-danger" href="{% url "patients:patient-list" %}">{% trans "Cancel" %}</a>
  {% endbuttons %}
</form>
{% endblock %}

patients/templates/patients/patient_detail.html
{% extends "patients/base.html" %}
{% load i18n %}

{% block content %}

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url "patients:index" %}">{% trans "Home" %}</a></li>
  <li class="breadcrumb-item"><a href="{% url "patients:patient-list" %}">{% trans "Patients" %}</a></li>
  <li class="breadcrumb-item active">{{ patient.full_name }}</li>
</ol>

<h1>{{ patient.full_name }}</h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">
      <a href="#patient_details" data-toggle="collapse">{% trans "Personal Information" %}</a>
    </h1>
  </div>

  <div class="collapse in" id="patient_details">
    <ul class="list-group">
      <li class="list-group-item">
        <a class="btn btn-primary" href="{% url "patients:patient-update" patient.id %}">{% trans "Update Personal Information" %}</a>
        <a class="btn btn-danger" href="{% url "patients:patient-delete" patient.id %}">{% trans "Remove Patient" %}</a>
      </li>

      <li class="list-group-item">
        <table class="table table-striped">
          <tr>
            <th>{% trans "Identification" %}</th>
            <td>{{ patient.identification }}</td>
          </tr>

          <tr>
            <th>{% trans "First Name" %}</th>
            <td>{{ patient.first_name }}</td>
          </tr>

          <tr>
            <th>{% trans "Last Name" %}</th>
            <td>{{ patient.last_name }}</td>
          </tr>

          <tr>
            <th>{% trans "Sex" %}</th>
            <td>{{ patient.sex_verbose }}</td>
          </tr>

          <tr>
            <th>{% trans "Date of Birth" %}</th>
            <td>{{ patient.date_of_birth }}</td>
          </tr>

          <tr>
            <th>{% trans "Age" %}</th>
            <td>{{ patient.age }}</td>
          </tr>

          <tr>
            <th>{% trans "Occupation" %}</th>
            <td>{{ patient.occupation }}</td>
          </tr>

          <tr>
            <th>{% trans "Phone Number" %}</th>
            <td>{{ patient.phone_number }}</td>
          </tr>
        </table>
      </li>

      <li class="list-group-item">
        <h2>{% trans "Address" %}</h2>
        <p>{{ patient.address }}</p>
      </li>
    </ul>
  </div>
</div>
{% endblock %}

patients/templates/patients/patient_form.html
{% extends "patients/base.html" %}
{% load i18n bootstrap3 %}

{% block content %}
<form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-success">{% trans "Submit" %}</button>
  <a class="btn btn-danger" href="{% url "patients:patient-list" %}">{% trans "Cancel" %}</a>
  {% endbuttons %}
</form>
{% endblock %}

patients/templates/patients/patient_list.html
{% extends "patients/base.html" %}
{% load i18n bootstrap3 %}

{% block content %}

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url "patients:index" %}">{% trans "Home" %}</a></li>
  <li class="breadcrumb-item active">{% trans "Patients" %}</li>
</ol>

<h1>{% trans "Patients" %}</h1>

<a class="btn btn-success" href="{% url "patients:patient-create" %}">{% trans "Add Patient" %}</a>

<table class="table">
  <thead>
    <tr>
      <th>{% trans "Identification" %}</th>
      <th>{% trans "First Name" %}</th>
      <th>{% trans "Last Name" %}</th>
      <th>{% trans "Options" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for patient in patient_list %}
    <tr>
      <td>{{ patient.identification }}</td>
      <td>{{ patient.first_name }}</td>
      <td>{{ patient.last_name }}</td>
      <td>
        <a href="{% url "patients:patient-detail" patient.id %}">{% bootstrap_icon "eye-open"%}</a>
        <a href="{% url "patients:patient-update" patient.id %}">{% bootstrap_icon "pencil"%}</a>
        <a href="{% url "patients:patient-delete" patient.id %}">{% bootstrap_icon "trash"%}</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}